# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Stuff
tagline:          'Lerwys'' Stuff'
description:      'My personal blog'
url:              http://lerwys.github.io/
baseurl:          /

author:
  name:           'Lucas Russo'
  url:            

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/lerwys/lerwys.github.io
