name: "My WebSite"
description: "My Personal Website"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
